language: mysql

# reduce clone time by only getting the latest commit and not the whole history (default for travis is 100)
git:
  depth: 1

# only run travis on the master branch
# branches:
#   only:
#     - master

before_script:
  - cd _tools
  - ./make_full_db.sh
  - ./make_full_locales_db.sh
  - mysql -e 'create database mangos;'

script:
  - mysql -u root mangos < full_db.sql
  - mysql -u root mangos < full_locales_db.sql
